name: futur
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core:
  firebase_auth:
  cloud_firestore:
  shared_preferences:
  google_sign_in:
  web_socket_channel:
  http:
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^24.1.41
  upi_india: ^3.0.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  video_player: ^2.8.3
  flutter_launcher_icons: ^0.13.1 # latest at time of writing


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/bt.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
